/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circuit;

public class App {
    protected Constant cons1;
    protected Constant cons2;
    protected And and;
    protected Or or;
    
    public String getGreeting() {
        this.cons1 = new Constant(false);
        this.cons2 = new Constant(true);
        this.and = new And();
        this.and.setOperand(cons1, cons2);
        this.or = new Or();
        or.setOperand(cons1, new Constant(this.and.getResult()));  
        return String.valueOf(or.getResult());
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}


