/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package circuit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CircuitTest {
    @Test
    void andX1TrueX2False() {
        CircuitFactory factory = new CircuitFactory();
        Constant cons1 = factory.getTrueConstant();
        Constant cons2 = factory.getFalseConstant();
        And and = factory.getAnd(cons1, cons2);
        assertFalse(and.getResult());
    }
}
